version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=calaca
      - MYSQL_PASSWORD=calaca
    networks:
      - net
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=calaca
      - MYSQL_PASSWORD=calaca
      - MYSQL_ROOT_PASSWORD='123456'
    networks:
      - net
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

volumes:

networks:
  net: